# Write your MySQL query statement below
SELECT EMPLOYEE_ID,DEPARTMENT_ID
FROM EMPLOYEE
WHERE EMPLOYEE_ID IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID
    HAVING COUNT(*)=1

) OR
primary_flag='Y'

