SELECT ROUND(COUNT(DISTINCT PLAYER_ID)/(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2) AS  fraction
FROM ACTIVITY
WHERE (PLAYER_ID,DATE_SUB(event_date,INTERVAL 1 DAY)) IN(
SELECT PLAYER_ID,MIN(event_date) AS SECOND_LOGG
FROM Activity
GROUP BY PLAYER_ID)
